Fix Nix build tests
The builds with older GCC should not use libraries (specifically fmt)
from Nixpkgs, which are built with newer GCC. It produces link errors
like this:

    /nix/store/p792j5f44l3f0xi7ai5jllwnxqwnka88-binutils-2.31.1/bin/ld: /nix/store/25gi6c955fshaqnyqpimh51wzshn82vb-spdlog-1.7.0/lib/libspdlog.a(fmt.cpp.o): in function `fmt::v6::system_error::init(int, fmt::v6::basic_string_view<char>, fmt::v6::format_args)':
    (.text+0xecb): undefined reference to `std::runtime_error::operator=(std::runtime_error&&)'

Therefore, we build those libraries from our submodules.